# Generated by Django 5.0.6 on 2024-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="postal_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
